-- ============================================================
-- Smart Retail Analytics Hub
-- OLTP Relational Schema
-- Oracle SQL
-- ============================================================

-- Customers
CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR2(100) NOT NULL,
    last_name   VARCHAR2(100) NOT NULL,
    email       VARCHAR2(255) UNIQUE,
    phone       VARCHAR2(50),
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Stores
CREATE TABLE stores (
    store_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name  VARCHAR2(100) NOT NULL,
    location    VARCHAR2(200),
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Products
CREATE TABLE products (
    product_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku           VARCHAR2(50) UNIQUE NOT NULL,
    product_name  VARCHAR2(200) NOT NULL,
    category      VARCHAR2(50),
    unit_price    NUMBER(10,2) NOT NULL
);

-- Inventory
CREATE TABLE inventory (
    store_id      NUMBER NOT NULL,
    product_id    NUMBER NOT NULL,
    qty_on_hand   NUMBER(10) DEFAULT 0,
    last_updated  TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT pk_inventory
        PRIMARY KEY (store_id, product_id),

    CONSTRAINT fk_inventory_store
        FOREIGN KEY (store_id)
        REFERENCES stores(store_id),

    CONSTRAINT fk_inventory_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);

-- Orders
CREATE TABLE orders (
    order_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     NUMBER REFERENCES customers(customer_id),
    store_id        NUMBER REFERENCES stores(store_id),
    order_datetime  TIMESTAMP DEFAULT SYSTIMESTAMP,
    order_status    VARCHAR2(30) DEFAULT 'PLACED',
    total_amount    NUMBER(12,2) DEFAULT 0
);

-- Order Items
CREATE TABLE order_items (
    order_item_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       NUMBER REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id     NUMBER REFERENCES products(product_id),
    quantity       NUMBER(10) DEFAULT 1,
    unit_price     NUMBER(10,2) NOT NULL
);
