-- ============================================================
-- Smart Retail Analytics Hub
-- OLAP Star Schema
-- Reconstructed from the project's dimensional model
-- Oracle SQL
-- ============================================================

-- Product Dimension
CREATE TABLE dim_product (
    product_key   NUMBER PRIMARY KEY,
    sku           VARCHAR2(50),
    product_name  VARCHAR2(200),
    category      VARCHAR2(50),
    unit_price    NUMBER(10,2)
);

-- Customer Dimension
CREATE TABLE dim_customer (
    customer_key  NUMBER PRIMARY KEY,
    first_name    VARCHAR2(100),
    last_name     VARCHAR2(100),
    email         VARCHAR2(255)
);

-- Store Dimension
CREATE TABLE dim_store (
    store_key   NUMBER PRIMARY KEY,
    store_name  VARCHAR2(100),
    location    VARCHAR2(200)
);

-- Time Dimension
CREATE TABLE dim_time (
    time_key     NUMBER PRIMARY KEY,
    the_date     DATE,
    year_num     NUMBER(4),
    month_num    NUMBER(2),
    day_of_week  VARCHAR2(20)
);

-- Sales Fact Table
CREATE TABLE fact_sales (
    sale_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       NUMBER,
    time_key       NUMBER NOT NULL,
    product_key    NUMBER NOT NULL,
    customer_key   NUMBER,
    store_key      NUMBER,
    units_sold     NUMBER(10),
    sales_revenue  NUMBER(12,2),

    CONSTRAINT fk_fact_time
        FOREIGN KEY (time_key)
        REFERENCES dim_time(time_key),

    CONSTRAINT fk_fact_product
        FOREIGN KEY (product_key)
        REFERENCES dim_product(product_key),

    CONSTRAINT fk_fact_customer
        FOREIGN KEY (customer_key)
        REFERENCES dim_customer(customer_key),

    CONSTRAINT fk_fact_store
        FOREIGN KEY (store_key)
        REFERENCES dim_store(store_key)
);
